/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const _kFontPkg = null;

  static const IconData starred = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_fill = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pen_btn = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData desktop = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_add = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData md_call = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsaapp_sm = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sm_call = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData data = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sm_camera = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recorder = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData double_tick = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chats_outline = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData status = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_filled = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_filled = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData archive = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chats = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pc = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsapp = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifcation = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData data_1 = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_i = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like_1 = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
