/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const _kFontPkg = null;

  static const IconData call = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_filled = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chats = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_filled = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData status = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chats_outline = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sm_camera = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recorder = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData double_tick = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
